### ISSUE TITLE
Not working on latest UI change

### ISSUE THREAD

**Issue by emostar** [davidmvenegas/chatgpt-microphone#59]
The following JS error is appearing in the console:

```
contentScript.js:165 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at main (contentScript.js:165:16)
    at checkScreenSize (contentScript.js:341:9)
    at contentScript.js:426:1
```

It looks like this code:

```
    // select parent element and send button
    const chatboxParentElement = chatboxElement.parentNode;
    const sendButton = chatboxParentElement.querySelector('button:nth-child(2)');
```

Needs to be changed to:
```
    // select parent element and send button
    const chatboxParentElement = chatboxElement.parentNode.parentNode;
    const sendButton = chatboxParentElement.querySelector('button:nth-child(3)');
```

I'm not sure how to modify the chrome extension code and test it out to make a PR. If you have instructions for that I can do it properly.

**Comment by davidmvenegas** [comment]
Oh man, good catch. I hadn't noticed until a few minutes ago that it was broken. I'll submit the fix right now

**Comment by emostar** [comment]
I figured out how to get a chrome extension running from source, but it looks like the above fix is not working.

**Comment by davidmvenegas** [comment]
yup, the latest update did a lot of damage, debugging now

**Comment by emostar** [comment]
One person's progress is another's damage ;)

The audio works fine for me with the PR I submitted. I haven't ever used snippets though, so you may want to check it out, but just the HTML structure change was the immediate breakage.

BTW, what do you use snippets for? I can't think of a situation for myself to use it.

**Comment by davidmvenegas** [comment]
Checked everything, it looks great, merging. I use snippets for phrases I have to say/type a lot, like for separating sections of text I'll just say "segment" and it'll insert the following (paragraph break + "---" + paragraph break):

---

That and other long sentences that I've found myself repeating

**Comment by emostar** [comment]
Cool, thanks for the info. I'll see if I can find some instances where I'm repeating myself.
